using Aeonpulse.Attributes;
using Microsoft.UI.Xaml;

namespace Aeonpulse.WinUI;

/// <summary>
/// WinUI 3 application class that hosts the MAUI app on Windows.
/// <see cref="InitializeComponent"/> is generated by WinUI from
/// <c>Platforms\Windows\App.xaml</c> and wires up WinUI's application resources.
///
/// <para>
/// <b>Execution order:</b> this constructor runs before <see cref="Aeonpulse.App"/>,
/// which in turn runs before <see cref="MauiProgram.CreateMauiApp"/>.
/// Theme and font-size preferences are therefore applied inside <see cref="Aeonpulse.App"/>
/// rather than here.
/// </para>
/// </summary>
[AIContext("PlatformEntryPoint")]
public partial class App : MauiWinUIApplication
{
    /// <summary>
    /// Initialises the WinUI application object - the Windows equivalent of
    /// <c>main()</c> / <c>WinMain()</c>.
    /// </summary>
    public App()
    {
        this.InitializeComponent();
    }

    /// <inheritdoc />
    protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
}

